{% set name = "types-pyOpenSSL" %}
{% set version = "23.2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-pyOpenSSL-{{ version }}.tar.gz
  sha256: beeb5d22704c625a1e4b6dc756355c5b4af0b980138b702a9d9f932acf020903

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-cryptography

test:
  commands:
    - test -f $SP_DIR/OpenSSL-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pyOpenSSL
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
