{% set version = "24.1.0.20240722" %}

package:
  name: types-pyopenssl
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-pyopenssl/types-pyOpenSSL-{{ version }}.tar.gz
  sha256: 47913b4678a01d879f503a12044468221ed8576263c1540dcb0484ca21b08c39

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cryptography >=35.0.0
    - python >={{ python_min }}
    - types-cffi

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/OpenSSL-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pyOpenSSL
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
